import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

const PhotoItem = ({item}) => {
	return (
		<Link href={`/photo/${item.id}`}>
			<li style={{width: '200px', display: 'flex', flexDirection: 'column', cursor: 'pointer'}}>
				<img src={item.thumbnailUrl} style={{height: '100px'}} />
				<span>{item.title}</span>
			</li>
		</Link>
	);
};

export default function Home({photoList}) {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<ul style={{listStyle: 'none', display: 'flex', flexWrap: 'wrap', gap: '20px'}}>
				{photoList?.map((item) => (
					<PhotoItem key={item.id} item={item} />
				))}
			</ul>
		</div>
	);
}

export const getServerSideProps = async () => {
	const response = await fetch('https://jsonplaceholder.typicode.com/photos?_start=1&_end=10');
	const photoList = await response.json();

	return {
		props: {
			photoList,
		},
	};
};
